[
  {
    "number": 792,
    "title": "FileNotFoundError: [WinError 2]",
    "created_at": "2025-02-17T06:21:27Z",
    "closed_at": "2025-02-17T17:13:51Z",
    "labels": [
      "help wanted"
    ],
    "url": "https://github.com/SWivid/F5-TTS/issues/792",
    "body": "### Checks\n\n- [x] This template is only for usage issues encountered.\n- [x] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.\n- [x] I have searched for existing issues, including closed ones, and couldn't find a solution.\n- [x] I confirm that I am using English to submit this report in order to facilitate communication.\n\n### Environment Details\n\nwhen i click synthesize i get this error :(\n\n\n\nFileNotFoundError: [WinError 2] The system cannot find the file specified\n\n### Steps to Reproduce\n\ni did everything the documentation said exactly and everything was going fine until i actually tried to run the synthesize button\n\n### \u2714\ufe0f Expected Behavior\n\nWorking, generating audio\n\n### \u274c Actual Behavior\n\nError, nothing happens",
    "comments_url": "https://api.github.com/repos/SWivid/F5-TTS/issues/792/comments",
    "author": "SulaimanBasal",
    "comments": [
      {
        "user": "SWivid",
        "created_at": "2025-02-17T06:23:18Z",
        "body": "> FileNotFoundError: [WinError 2] The system cannot find the file specified\n\nmake sure you have fully upload the audio"
      },
      {
        "user": "SulaimanBasal",
        "created_at": "2025-02-17T06:26:20Z",
        "body": "@SWivid i did, i can even listen to it in the ui... (thanks for the fast reply)\n"
      },
      {
        "user": "SWivid",
        "created_at": "2025-02-17T06:29:37Z",
        "body": "you could probably provide more details as suggest by the issue template.\notherwise we could hardly help cuz no info"
      },
      {
        "user": "SulaimanBasal",
        "created_at": "2025-02-17T06:36:24Z",
        "body": "@SWivid yea i'm sorry about that, i'm a total noob at this... \n\nthis is the full message when i upload, will that help?\n\n\nC:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\pydub\\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work\n  warn(\"Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work\", RuntimeWarning)\nTraceback (most recent call last):\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\gradio\\queueing.py\", line 625, in process_events\n    response = await route_utils.call_process_api(\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\gradio\\route_utils.py\", line 322, in call_process_api\n    output = await app.get_blocks().process_api(\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\gradio\\blocks.py\", line 2051, in process_api\n    result = await self.call_function(\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\gradio\\blocks.py\", line 1598, in call_function\n    prediction = await anyio.to_thread.run_sync(  # type: ignore\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2461, in run_sync_in_worker_thread\n    return await future\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 962, in run\n    result = context.run(func, *args)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\gradio\\utils.py\", line 883, in wrapper\n    response = f(*args, **kwargs)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\f5_tts\\infer\\infer_gradio.py\", line 241, in basic_tts\n    audio_out, spectrogram_path, ref_text_out = infer(\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\f5_tts\\infer\\infer_gradio.py\", line 131, in infer\n    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\f5_tts\\infer\\utils_infer.py\", line 294, in preprocess_ref_audio_text\n    aseg = AudioSegment.from_file(ref_audio_orig)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\pydub\\audio_segment.py\", line 728, in from_file\n    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\site-packages\\pydub\\utils.py\", line 274, in mediainfo_json\n    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\subprocess.py\", line 971, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"C:\\Users\\SUL\\.conda\\envs\\f5\\lib\\subprocess.py\", line 1456, in _execute_child\n    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,\nFileNotFoundError: [WinError 2] The system cannot find the file specified\n\n\n\n\n\n\n---\n\n@SWivid also when starting the gradio app  i get this before given the local link:\nStarting app...\nINFO: Could not find files for the given pattern(s).\n\nwould that be what's causing the issue?"
      },
      {
        "user": "SWivid",
        "created_at": "2025-02-17T06:52:06Z",
        "body": "> C:\\Users\\SUL.conda\\envs\\f5\\lib\\site-packages\\pydub\\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work\n\nmay try #739 \ninstall ffmpeg"
      },
      {
        "user": "SulaimanBasal",
        "created_at": "2025-02-17T17:13:51Z",
        "body": "@SWivid Yep!!! that was the issue hahaha, it's weird that it didn't tell me that it was missing as an error but anyway thanks for the fast reply, installing the ffmpeg and the ffmpeg python fixed it and now works like a charm! thank you again, and great job on the tool, much appreciate it!"
      }
    ],
    "satisfaction_conditions": [
      "Identifies the missing dependency causing the FileNotFoundError during audio processing",
      "Explains why the error occurs despite valid UI file uploads",
      "Ensures audio processing tools are properly accessible in the execution environment"
    ],
    "_classification": {
      "category": "Requires build environment but hard to be dockerized",
      "timestamp": "2025-04-05 02:12:03"
    }
  },
  {
    "number": 190,
    "title": "Broken on MPS",
    "created_at": "2024-10-20T19:29:57Z",
    "closed_at": "2024-10-20T20:06:10Z",
    "labels": [],
    "url": "https://github.com/SWivid/F5-TTS/issues/190",
    "body": "Not sure what happened, but looks like the app is broken on Macs at the moment.\r\n\r\nJust did a fresh install and the app itself runs, but the resulting audio is empty.\r\n\r\nAlso I am not sure if the logs are useful but pasting just in case:\r\n\r\n```\r\n/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py:496: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.\r\n  warnings.warn(\r\nYou have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.\r\n\r\nPassing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.\r\nThe attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.\r\ngen_text 0 Reference text will be automatically transcribed with Whisper if not provided. For best results, keep your reference clips short\r\nBuilding prefix dict from the default dictionary ...\r\nLoading model from cache /Users/x/pinokio/cache/TMPDIR/jieba.cache\r\nLoading model cost 0.426 seconds.\r\nPrefix dict has been built successfully.\r\n/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/processing_utils.py:574: UserWarning: Trying to convert audio automatically from float32 to 16-bit int format.\r\n  warnings.warn(warning.format(data.dtype))\r\n/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/processing_utils.py:577: RuntimeWarning: invalid value encountered in cast\r\n  data = data.astype(np.int16)\r\n```\r\n\r\nI am not completely sure but I don't remember seeing this many warning messages previously.",
    "comments_url": "https://api.github.com/repos/SWivid/F5-TTS/issues/190/comments",
    "author": "cocktailpeanut",
    "comments": [
      {
        "user": "SWivid",
        "created_at": "2024-10-20T19:35:37Z",
        "body": "a default fp16 inference setting was added.\r\nsee if the last commit works d3badb95cf1b97a61472d65d4787a35cddf9c908"
      },
      {
        "user": "cocktailpeanut",
        "created_at": "2024-10-20T19:48:06Z",
        "body": "@SWivid this worked, thank you!\r\n\r\nCould you share what the switch to fp16 means from end user's point of view (performance, etc.)? Appreciate it!"
      },
      {
        "user": "SWivid",
        "created_at": "2024-10-20T20:05:25Z",
        "body": "> Could you share what the switch to fp16 means from end user's point of view (performance, etc.)? Appreciate it!\r\n\r\nA bit faster than using fp32, ~half graphics card usage (the %), and more environmentally friendly maybe lol\r\nCompared to a more aggressive int8 quantization, it can be seen as no performance (quality) penalty."
      },
      {
        "user": "cocktailpeanut",
        "created_at": "2024-10-20T20:06:10Z",
        "body": "Thank you!"
      }
    ],
    "satisfaction_conditions": [
      "Resolves empty audio output issue on macOS",
      "Explains performance implications of technical changes in non-technical terms",
      "Addresses compatibility with Apple's Metal Performance Shaders (MPS)",
      "Maintains audio quality while optimizing resource usage"
    ],
    "_classification": {
      "category": "Requires build environment but hard to be dockerized",
      "timestamp": "2025-04-05 02:14:54"
    }
  }
]