[
  {
    "number": 65,
    "title": "Fixed similarity_percentile with sdpm chunker + added test",
    "created_at": "2024-11-25T04:32:40Z",
    "closed_at": "2024-12-06T23:01:47Z",
    "labels": [],
    "url": "https://github.com/chonkie-ai/chonkie/pull/65",
    "body": "`similarity_percentile` was not working with spdm chunker because the `similarity_threshold` was not computed. I have added test to reproduce the same.\r\n\r\n**Fix**\r\nI moved the computation `similarity_threshold` into `_prepare_sentences`. This decouples the computation of `similarity_threshold` with other steps.",
    "comments_url": "https://api.github.com/repos/chonkie-ai/chonkie/issues/65/comments",
    "author": "pratyushmittal",
    "comments": [
      {
        "user": "bhavnicksm",
        "created_at": "2024-11-26T15:44:13Z",
        "body": "Hey @pratyushmittal!\r\n\r\nThanks for submitting a PR! \ud83d\ude0a\r\n\r\nSorry, just been involved with some work, so it might take a while, I'll review this PR as soon as possible again. \r\n\r\nThanks!"
      },
      {
        "user": "pratyushmittal",
        "created_at": "2024-12-04T04:40:29Z",
        "body": "Hey @bhavnicksm, please let me know if you need any help in this PR.\r\n\r\nI am loving Chonkie. I want to try out `similarity_percentile` in `sdpm_chunker`. That is currently broken. This PR fixes it."
      },
      {
        "user": "bhavnicksm",
        "created_at": "2024-12-06T23:01:47Z",
        "body": "Hey @pratyushmittal! \r\n\r\nSorry for the delayed response, I've been involved in some other aspects so couldn't look at this earlier. \ud83d\ude05\r\n\r\nI see the issue you mentioned here, and I don't think it has anything to do with decoupling than with not storing the `similarity_threshold` once computed. \r\n\r\nI added a patch fix for it by converting `similarity_threshold` to `self.similarity_threshold`, and it passes the test. \r\n\r\nIf you could refactor the PR to have a function in the class called `_compute_similarity_threshold` and then call it inside the `chunk` fn then, I could go ahead with merging the PR. \r\n\r\nIf not, I can add a patch for that in later versions. \r\n\r\nThanks~ \ud83d\ude0a\n\n---\n\nHey @pratyushmittal!\r\n\r\nClosing this since I added a fix in #79 \u2014 this PR wouldn't have been possible without you pointing out the issue and emphasizing it.\r\n\r\nThank you so much for the PR~ Looking fwd to future contributions from you as well \ud83d\ude0a\r\n\r\nThanks! \r\n"
      },
      {
        "user": "pratyushmittal",
        "created_at": "2024-12-07T06:27:09Z",
        "body": "This is so good @bhavnicksm. Thanks a lot for reviewing the PR, providing the feedback and pushing the fix.\r\n\r\nYou are doing a wonderful work \ud83d\ude4c\ud83c\udffd!"
      }
    ]
  },
  {
    "number": 33,
    "title": "[BUG] TypeError: dataclass() got an unexpected keyword argument 'slots'",
    "created_at": "2024-11-18T05:12:55Z",
    "closed_at": "2024-11-18T07:16:17Z",
    "labels": [
      "bug"
    ],
    "url": "https://github.com/chonkie-ai/chonkie/issues/33",
    "body": "**Describe the bug**\r\nWhen I do a `from chonkie import TokenChunker` I get the error\r\n\r\n**To Reproduce**\r\nRun `from chonkie import TokenChunker` after a fresh install\r\n\r\n**Expected behavior**\r\nThe TokenChunker package should be imported without errors\r\n\r\n**Screenshots**\r\n```\r\nDownloading chonkie-0.2.0-py3-none-any.whl (23 kB)\r\nDownloading autotiktokenizer-0.2.1-py3-none-any.whl (8.9 kB)\r\nInstalling collected packages: autotiktokenizer, chonkie\r\nSuccessfully installed autotiktokenizer-0.2.1 chonkie-0.2.0\r\n(.llm_vnev) mis@mispl-lap-163:~ $ python3\r\nPython 3.8.10 (default, Sep 11 2024, 16:02:53) \r\n[GCC 9.4.0] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> from chonkie import TokenChunker\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/__init__.py\", line 1, in <module>\r\n    from .chunker import (BaseChunker, Chunk, SDPMChunker, SemanticChunk,\r\n  File \"/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/chunker/__init__.py\", line 1, in <module>\r\n    from .base import BaseChunker, Chunk\r\n  File \"/home/mis/Documents/docxtract/llm/.llm_vnev/lib/python3.8/site-packages/chonkie/chunker/base.py\", line 9, in <module>\r\n    @dataclass(slots=True)\r\nTypeError: dataclass() got an unexpected keyword argument 'slots'\r\n```\r\n\r\n**Additional context**\r\nDid a fresh install using `pip install chonkie` and tried to run the tool based on the given guide.\r\n\r\nAnything that I did is wrong?\r\n",
    "comments_url": "https://api.github.com/repos/chonkie-ai/chonkie/issues/33/comments",
    "author": "AgentT30",
    "comments": [
      {
        "user": "bhavnicksm",
        "created_at": "2024-11-18T06:44:39Z",
        "body": "Hey @AgentT30!\r\n\r\nThanks for raising an issue \ud83d\ude0a\r\n\r\nThe issue is with Python slots, which were introduced first in python3.10 as the parameter that I am using inside the `dataclass`. Before that, it was `__slots__` for versions 3.8 and 3.9, which needs to be added in the codebase.\r\n\r\nIt seems like it got missed as an error. As a workaround for now, could you try it with Python 3.10? \r\n\r\nI'll add a backward compatible version of slots into Chonkie in a patch release as soon as possible.\r\n\r\nThanks! "
      },
      {
        "user": "AgentT30",
        "created_at": "2024-11-18T06:53:26Z",
        "body": "@bhavnicksm Works with python 3.10 and above.\r\n\r\nThanks!"
      }
    ]
  }
]